CREATE TABLE cart_details
(
    id      	BIGSERIAL       PRIMARY KEY,
	cart_id	INTEGER    NOT NULL,
	product_id INTEGER    NOT NULL,
	quantity INTEGER    NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    deleted_at TIMESTAMP WITH TIME ZONE DEFAULT NULL
);